### ISSUE TITLE
media

### ISSUE THREAD

**Issue by habamax** [habamax/vim-habaurora#1]
![image](https://user-images.githubusercontent.com/234774/158125102-f5a7559a-8457-4074-8ba6-972d1bc1e414.png)

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/159722892-07b5f900-a3c6-40c0-a084-16fc8030fe28.png)

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/161539799-eff87177-0df0-4716-bdb1-63f0e73bf2c2.png)

**Comment by craigmac** [comment]
How I do I get that one? Perfect for today, I'll try it out.

**Comment by habamax** [comment]
It is in the repo, but only works for GUI and termguicolors. For 256c term it behaves as `habalbum`
