### ISSUE TITLE
TabLineSel no defined on startup

### ISSUE THREAD

**Issue by craigmac** [habamax/vim-habaurora#2]
In my config I have `set showtabline=2` so tabpages are there second Vim loads. With this setting it seems `TabLineSel` doesn't colour it correctly until I do a `:tabnew`, and then the colours kick in and everything is correct.

This didn't happen with Apprentice, so I started looking at what it did differently. When I add

```
if exists('syntax_on')
  syntax reset
endif
```

just after the `hi clear`, I get the behaviour I want (TabLineSel group is coloured properly on startup).

When I start vim and check `:hi TabLineSel` immediately, all I see is `TablineSel     xxx term=bold`. It's not getting defined right away for some reason. Dropping the above snippet fixes it, but is this a bigger colortemplate issue?

**Comment by habamax** [comment]
Interesting, I can't see the difference having `set showtabline=2`:

![image](https://user-images.githubusercontent.com/234774/159637687-e2128279-d855-4aa9-817b-e30454f22d98.png)

And on wsl vim (terminal) `:hi TablineSel` after vim startup is
![image](https://user-images.githubusercontent.com/234774/159637823-1ac4e725-baaa-4c10-8835-c674145de328.png)

And on gvim on windows it is:

![image](https://user-images.githubusercontent.com/234774/159637903-7d6ca7b7-0a50-4999-a61c-051a61219f0a.png)

Which should not have effect for gui anyway.


`term` value has no effect on colored terminals and gui, for `cterm` and `gui` I set everything for `NONE`.

**Comment by habamax** [comment]
I have explicitly set colors for TabLineSel, could you check the latest?

**Comment by craigmac** [comment]
How it looked at startup:

<img width="2025" alt="Screen Shot 2022-03-22 at 9 31 14 PM" src="https://user-images.githubusercontent.com/7416158/159697078-2ace614d-431b-49db-81a8-490f7edd72e8.png">

Running `:hi TabLineSel` right after startup, ctermfg/bg not set:

<img width="590" alt="Screen Shot 2022-03-22 at 9 33 46 PM" src="https://user-images.githubusercontent.com/7416158/159697153-d0d475ce-8f49-4cae-93b2-40a00d8157ec.png">

After running `:tabnew` the whole tabline now is coloured correctly:

<img width="2025" alt="Screen Shot 2022-03-22 at 9 31 36 PM" src="https://user-images.githubusercontent.com/7416158/159697302-6e1c33a5-e077-41d8-9345-f8ecc825e94b.png">

**Comment by habamax** [comment]
Yeah, I was assuming it somehow takes the fg and bg of your terminal (but for my terminal it was still ok).

So was it fixed for you with the latest change?

**Comment by craigmac** [comment]
Yes, just tested it, works fine now, thanks! Is this a colortemplate bug though?

**Comment by habamax** [comment]
BTW, I have "internal" variation `habalbum` with pure white bg, if you are interested :)

![image](https://user-images.githubusercontent.com/234774/159698161-1416ffd7-fc47-4527-bc07-96217727f4ca.png)

**Comment by habamax** [comment]
> Yes, just tested it, works fine now, thanks! Is this a colortemplate bug though?

Well, idk. It should take bg of the normal highlight group if you set `NONE` to any other, like if

```
hi Statement ctermbg=NONE ctermfg=red
```
set then Statement should have whatever bg of the `Normal`.

It doesn't work for TabLineSel though, so I have explicitly set it to what Normal has.

PS, Or rather it works for my vim in whatever terminals I use, but not for you :)

**Comment by craigmac** [comment]
Oooh, yes please! I have toyed with pure white bg and I do like it better. I love that visual mode highlight so much more than the green one. One small thing as well, I find the QuickfixLine highlight oddly out of place because it's blue an no other search-type things are like that. I took a cue from apprentice and linked QuickfixLine to Search.

**Comment by habamax** [comment]
habaurora has blue too but you have to turn on `termguicolors` for that.

**Comment by craigmac** [comment]
Ah ok, I usually use Terminal.app, which is limited to 256 (in the year 2022...).

**Comment by habamax** [comment]
> I took a cue from apprentice and linked QuickfixLine to Search

It is not very good from "usability" perspective. Imagine you do a search in quickfix window... That is why QuickFixLine is distinct there (it was the same as cursorline but then you can't figure out what is active quickfixline, what is cursorline)

![image](https://user-images.githubusercontent.com/234774/159699387-d075fa9f-55eb-4af1-8d6e-e0ab116234c0.png)

**Comment by craigmac** [comment]
Just testing the new github.com/vim/colorschemes and the same problem exists with TabLineSel with all the colorschemes I've tested, I'll file an issue there. And thanks, that make sense I never search the quickfix.

**Comment by habamax** [comment]
> Oooh, yes please! I have toyed with pure white bg and I do like it better

https://github.com/habamax/.vim/tree/master/pack/local/start/vim-habalbum

Not yet published, as I like to play with it a bit more.
But it is essentially the same as this one with white (album in latin ;) ) bg and tuned surrounded colors like pmenu, cursorline, folded etc.

**Comment by habamax** [comment]
Most probably I will add it here as a second variant in the future.

**Comment by habamax** [comment]
@craigmac and it is here :)
